services:
  sqlserver:
    environment:
      - SA_PASSWORD=${SA_PASSWORD:-Cryptography@123}
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./backups:/var/opt/mssql/backup
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  cryptography-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ConnectionString=${DB_CONNECTION_STRING:-Data Source=sqlserver,1433;Initial Catalog=CryptographyDb;User ID=SA;Password=Cryptography@123;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=True;MultipleActiveResultSets=True;}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  sqlserver_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryptography/data
